
ALTER TABLE Delivery
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Employee
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Holiday
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Pay
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Post
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Subdivision
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Vacation
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE Weekend
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;

ALTER TABLE WorkingHours
ADD UCR NVARCHAR(20) NULL, 
DCR DATETIME NULL, 
ULC NVARCHAR(20) NULL, 
DLC DATETIME NULL;
