
-- INSERT

CREATE TRIGGER PayCreateUserAndDate
ON Pay
AFTER INSERT
AS
BEGIN
	DECLARE @id INT
	DECLARE mycursor CURSOR FAST_FORWARD FOR 
	SELECT PayId FROM inserted
	OPEN mycursor
	FETCH NEXT FROM mycursor into @id
	WHILE @@FETCH_STATUS=0
	BEGIN
		UPDATE Pay SET UCR = CURRENT_USER,
		DCR=GETDATE() 
		WHERE PayId = @id
	FETCH NEXT FROM mycursor into @id
	END
CLOSE mycursor
DEALLOCATE mycursor
END

-- UPDATE

CREATE TRIGGER PayUpdateUserAndDate
ON Pay
AFTER UPDATE
AS
BEGIN
	UPDATE Pay SET ULC = CURRENT_USER,
	DLC=GETDATE() 
	WHERE PayId = (
		SELECT PayId from inserted
	)
END
